export const GUEST_READY_MARKER = "[webagent] guest ready";

export function buildGuestInitScript(): string {
  return [
    "#!/bin/sh",
    'echo "[webagent] rootfs remount…"',
    "mount -o remount,size=4G / >/dev/null 2>&1 || true",
    '[ -f /etc/network/interfaces ] || { mkdir -p /etc/network 2>/dev/null; printf "%s\\n" "auto lo" "iface lo inet loopback" "" "auto eth0" "iface eth0 inet manual" > /etc/network/interfaces; }',
    "ip link set eth0 up 2>/dev/null",
    "ifconfig lo 127.0.0.1 up 2>/dev/null || ip link set lo up 2>/dev/null",
    "udhcpc -i eth0 -q -n -f -T 2 -t 3 >/dev/null 2>&1 || true",
    'sed -i "/# webagent-doh-begin/,/# webagent-doh-end/d" /etc/hosts 2>/dev/null',
    '{ echo "# webagent-doh-begin"; for h in linuxontab.com relay.linuxontab.com dl-cdn.alpinelinux.org; do',
    '  ip=$(wget -qO- --timeout=6 -t 1 "https://relay.linuxontab.com/cors?url=https%3A%2F%2F1.1.1.1%2Fdns-query%3Fname%3D${h}%26type%3DA"',
    '    2>/dev/null | tr "," "\\n" | sed -n \'s/.*"data":"\\([0-9.]*\\)".*/\\1/p\'',
    '    | grep -E "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$" | head -1)',
    '  [ -z "$ip" ] && ip=$(wget -qO- --timeout=4 -t 1 "https://1.1.1.1/dns-query?name=${h}&type=A"',
    '    --header="Accept: application/dns-json" 2>/dev/null',
    '    | tr "," "\\n" | sed -n \'s/.*"data":"\\([0-9.]*\\)".*/\\1/p\'',
    '    | grep -E "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$" | head -1)',
    '  [ -n "$ip" ] && echo "$ip $h"',
    'done; echo "# webagent-doh-end"; } >> /etc/hosts',
    'echo "[webagent] network ready"',
    'echo "[webagent] dns-seed done"',
    "if ! command -v unbound >/dev/null 2>&1; then apk add --no-cache unbound >/dev/null 2>&1 || echo '[webagent] unbound install failed' >&2; fi",
    "mkdir -p /etc/unbound /var/lib/unbound 2>/dev/null",
    "printf '%s\\n' 'server:' '  interface: 127.0.0.1' '  port: 53' '  do-udp: yes' '  do-tcp: yes' '  chroot: \"\"' '  use-syslog: no' 'forward-zone:' '  name: \".\"' '  forward-tcp-upstream: yes' '  forward-addr: 1.1.1.1' '  forward-addr: 1.0.0.1' > /etc/unbound/unbound.conf",
    "killall -q unbound 2>/dev/null; sleep 1",
    "unbound -c /etc/unbound/unbound.conf >/dev/null 2>&1 & sleep 1",
    "printf 'nameserver 127.0.0.1\\nnameserver 1.1.1.1\\n' > /etc/resolv.conf",
    'echo "[webagent] dns proxy ready"',
    "(rdate -s 1.1.1.1 2>/dev/null || ntpd -dnq -p pool.ntp.org >/dev/null 2>&1) && echo '[webagent] time synced' || echo '[webagent] time sync failed' >&2",
    'printf "%s\\n" "https://dl-cdn.alpinelinux.org/alpine/v3.21/main" "https://dl-cdn.alpinelinux.org/alpine/v3.21/community" > /etc/apk/repositories',
    'echo "[webagent] apk update…"',
    "(timeout 600 apk update 2>&1 | tail -5) || echo '[webagent] apk update failed'",
    'echo "[webagent] apk update done"',
    'echo "[webagent] installing nodejs + python3…"',
    "(timeout 600 apk add --no-cache nodejs npm python3 py3-pip bash 2>&1 | tail -8) || echo '[webagent] package install failed'",
    'echo "[webagent] packages installed"',
    "mkdir -p /workspace",
    `echo "${GUEST_READY_MARKER}"`,
    "",
  ].join("\n");
}
